name: Continuous Integration
on:
  pull_request:
    branches:
      - main
jobs:
  build: # nome
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        # ate aqui é o pseudo-padrao
        # baixa o código a VM do workflow ??????
        
      - name: MegaLinter
        uses: oxsecurity/megalinter@v8.0.0

        # mais indicado que o pilint pois o codigo é multi-linguagem de programação
