name: Continuous Integration
on:
  pull_request:
    branches:
      - main
jobs:
  build: # nome
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        # ate aqui é o pseudo-padrao
        # baixa o código a VM do workflow ??????
        
      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.1
        # lint simples

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # boa pratica segundo a literatura e pesquisas

      - name: Install dependencies # boa pratica segundo a literatura e pesquiass
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # uma action que faz um ping em um site a escolha, pode inclusive ser salvo como SECRET
      - name: Ping URL
        uses: nerdify/ping-action@1.0.0
        env:
          PING_URL: "https://www.google.com"

      # action que verifica vulnerabilidade nas dependencias
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4

  # build docker sem push
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: user/app:latest

  discord:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Discord Commits
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true
