name: Continuous Integration
on:
  pull_request:
    branches:
      - main
jobs:
  build: # nome
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        # ate aqui é o pseudo-padrao
        # baixa o código a VM do workflow ??????
        
      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.1
        # lint simples

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # boa pratica segundo a literatura e pesquisas

      - name: Install dependencies # boa pratica segundo a literatura e pesquiass
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get system information
        uses: jakejarvis/system-information-action@v1


